FROM klokantech/openmaptiles-server

WORKDIR /data
RUN wget -c https://openmaptiles.com/download/WyI4NWE5ZjM3Yi1lODcwLTRlYTAtOGNkYy03MWE3YWI3ZjI2NGQiLCItMSIsODc2NV0.Xn0iXQ.DNgwYbnmn0VH2np-slMc3V9hpvM/osm-2017-07-03-v3.6.1-italy_centro.mbtiles?usage=personal
